sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tPPLDXJc8paQFeXHUvd
    access-key-secret: 6x9ktGxtZfJXDqSkQ9GcpHfE4Eci2H
    bucket-name: sakurayuki
